/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Mockup model module.
 * @module model/Mockup
 * @version 1.0.0
 */
class Mockup {
    /**
     * Constructs a new <code>Mockup</code>.
     * @alias module:model/Mockup
     * @param firstname {String} 
     * @param lastname {String} 
     */
    constructor(firstname, lastname) { 
        
        Mockup.initialize(this, firstname, lastname);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstname, lastname) { 
        obj['firstname'] = firstname;
        obj['lastname'] = lastname;
    }

    /**
     * Constructs a <code>Mockup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mockup} obj Optional instance to populate.
     * @return {module:model/Mockup} The populated <code>Mockup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mockup();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Mockup.prototype['_id'] = undefined;

/**
 * @member {String} firstname
 */
Mockup.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
Mockup.prototype['lastname'] = undefined;






export default Mockup;

